# Generated by Django 4.2.30 on 2026-08-28 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('local', 'Lokal'), ('apotekapps', 'ApotekApps')], default='local', max_length=20)),
                ('external_id', models.PositiveIntegerField(blank=True, help_text='ID user di ApotekApps (jika disinkron).', null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor Profile',
                'verbose_name_plural': 'Monitor Profiles',
            },
        ),
    ]
