# Generated by Django 4.2.30 on 2026-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorprofile',
            name='apotek_access',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='apotek_refresh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='apotek_token_exp',
            field=models.FloatField(default=0.0),
        ),
    ]
