# Generated by Django 4.2.30 on 2026-08-22 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('module', models.CharField(default='general', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('error', 'Error')], default='error', max_length=10)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('request_body', models.TextField(blank=True, default='')),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(default='manual', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='monitor.apiendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='monitor_api_status_59190a_idx'), models.Index(fields=['path', 'created_at'], name='monitor_api_path_8479cf_idx')],
            },
        ),
    ]
