# Generated by Django 4.2.30 on 2026-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_aiinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLayout',
            fields=[
                ('node_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
    ]
