# Generated by Django 4.2.30 on 2026-08-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0004_nodelayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.CharField(blank=True, default='', help_text='Base URL router AI (OpenAI-compatible), mis. http://localhost:20128/v1', max_length=255)),
                ('model', models.CharField(blank=True, default='', help_text='Nama router / model (mis. gpt-4o, atau nama router LiteLLM).', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(blank=True, default="You are the AI assistant for 'OrchestrationApps', a monitoring dashboard for the ApotekApps pharmacy backend (API, database, redis, nginx, webhooks). Answer in the user's language. Help with using the dashboard, interpreting metrics, and troubleshooting incidents.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Config',
                'verbose_name_plural': 'AI Config',
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('chat', 'Chatbot'), ('analysis', 'Analisis')], default='chat', max_length=20)),
                ('role', models.CharField(default='user', max_length=20)),
                ('content', models.TextField()),
                ('session_id', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(blank=True, default='chatbot_widget', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_ai_chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Log',
                'verbose_name_plural': 'AI Chat Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
