# Generated by Django 4.2.30 on 2026-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_aiconfig_aichatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlite_path', models.CharField(blank=True, default='', help_text='Path file db.sqlite3 Monitor. Kosongkan untuk default.', max_length=512)),
                ('pg_host', models.CharField(blank=True, default='', max_length=255)),
                ('pg_port', models.IntegerField(blank=True, null=True)),
                ('pg_name', models.CharField(blank=True, default='', max_length=255)),
                ('pg_user', models.CharField(blank=True, default='', max_length=255)),
                ('pg_password', models.CharField(blank=True, default='', max_length=255)),
                ('redis_url', models.CharField(blank=True, default='', help_text='redis://[:password@]host:port/db — kosongkan untuk default.', max_length=512)),
                ('ai_enabled', models.BooleanField(default=False)),
                ('ai_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('ai_model', models.CharField(blank=True, default='', max_length=100)),
                ('ai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connection Config',
                'verbose_name_plural': 'Connection Config',
            },
        ),
    ]
