# Generated by Django 5.1.15 on 2026-09-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_connectionconfig_secondary_pg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('until', models.DateTimeField(blank=True, help_text='Maintenance ends at this time (null = indefinite).', null=True)),
                ('service', models.CharField(default='ApotekApps API', help_text='Service undergoing maintenance (displayed to users).', max_length=120)),
                ('reason', models.TextField(blank=True, default='', help_text='Human-readable reason shown on the splash page.')),
                ('affected_services', models.TextField(blank=True, default='', help_text='Comma-separated list of affected endpoints/modules.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
    ]
